### ISSUE TITLE
log tail switch takes unusually long to return 

### ISSUE THREAD

**Issue by justinchinFR** [rockcarver/frodo-lib#29]
In v0.6.1 the cmd below starts printing results in a few seconds.  In v0.7.0 the same cmd takes several mins to begin returning results.

1. Run command from v0.7.0 `/frodo logs tail hc`
2. Run command from v0.6.1 `/frodo logs tail hc`

Expected behavior - The tail begins returning in roughly the same amount of time for either frodo versions.  

 - OS: macos

**Comment by atomicsamurai** [comment]
> In my case that log statement never shows up `logger.error('LOGGING TEST - onUpdate script')` with this command :
> 
> ```
> ✗ frodo logs tail -c idm-everything  patrick                                                    
> Tailing ID Cloud logs from the following sources: idm-everything and levels [SEVERE,ERROR,FATAL]...
> ```
> 
> I had to revert back to an earlier release that does not have the new -l option.

@patrickdiligent - as IDM logs record type is text/plain, filtering them by level does not work. So the default filter of `SEVERE,ERROR,FATAL` will not show such records.
You should see results when you use:
```
$ frodo logs tail -c idm-everything -l 4 patrick
```

**Comment by patrickdiligent** [comment]
Not true. First that issue has been fixed since. To mention that the REST interface to IDM logs has been lazily implemented, because __ALL__ IDM logs have a level - apparently it was too complicated to parse log statements that spread two lines 🤷‍♂️so everything is mapped to text/plain! The fix goes beyond by analysing the message for a level section. So with the latest frodo release, yes, -l works for IDM logs. If it is indeed possible to do this at the client level, why not at the source, server side!?

**Comment by vscheuber** [comment]
@atomicsamurai can we close this issue?
