### ISSUE TITLE
Ability to create/select scopes for Service Accounts

### ISSUE THREAD

**Issue by drlee123** [rockcarver/frodo-lib#391]
Platform UI does not allow fr:iga:* scope to be created for service accounts.  Need ability to add this scope to a service account when being created so /governance APIs can be called programmatically as March 1st will require tenant admins to have MFA so service accounts will need to have this scope for governance calls.

**Comment by vscheuber** [comment]
I'm going to implement an approach where Frodo creates service accounts with all allowed scopes. The UI still doesn't show additional scopes but [FRAAS-18971](https://bugster.forgerock.org/jira/browse/FRAAS-18971) was fixed in ID Cloud and thus these scopes are now available:
fr:am:*
fr:idc:analytics:*
fr:autoaccess:*
fr:idc:certificate:*
fr:idc:certificate:read
fr:idc:content-security-policy:*
fr:idc:custom-domain:*
fr:idc:esv:*
fr:idc:esv:read
fr:idc:esv:restart
fr:idc:esv:update
fr:idm:*
fr:iga:*
fr:idc:promotion:*
fr:idc:release:*
fr:idc:sso-cookie:*
